### PR TITLE
first shot at testing

### PR DESCRIPTION
**Pull request by NicolasDurrande**
Hi, 
I'm not familiar with "testthat" so let me know if you have any remark or suggestion. If you are happy with this I'll translate the rest of the file in the same fashion.

By the way, I didn't use the `with k.tf_mode():` trick:

the following python code

```
        x_free = tf.placeholder('float64')
        kernel.make_tf_array(x_free)
        X = tf.placeholder('float64')
        X_data = rng.randn(3, 1)
        reference_gram_matrix = referenceRbfKernel(X_data, lengthScale, variance)

        with kernel.tf_mode():
            gram_matrix = tf.Session().run(kernel.K(X), feed_dict={x_free: kernel.get_free_state(), X: X_data})
```

became

```
       X <- matrix(rnorm(3))
       cov_mat <- tf$Session()$run(kernel$K(X))
```

is there something wrong with this ?

### CODE REVIEW

**Comment by NicolasDurrande** [comment]
Looks like the build is not passing but I can't reproduce on my machine:
   test 1.  the build passes when I run locally 

```
library(testthat)
library(tensorflow)
library(gpflowr)
test_dir("tests/testthat")
```

 Test 2.  `R CMD check gpflower` returns an unrelated error : the fields ‘Author’ and ‘Maintainer’ are not specified in the DESCRIPTION file.

Any thoughts ?

**Comment by goldingn** [comment]
Hey, sorry I missed this PR - for some reason I didn't get a notification and only just spotted it!

Yeah, your tests work fine locally for me too.

It looks like the problem is dodgy tensorflow installation on travis:
https://travis-ci.org/goldingn/gpflowr/jobs/168927169#L1001

which looks like it should be fixed by installing `libc6`. I'll have a bash at that and see if it fixes the problems

**Comment by goldingn** [comment]
I've tried a bunch of things and can't get the R API to link to TF on Travis.

I just realised that the travis build for the R API is also failing to link to TF, and is just skipping all tests that need to execute graphs (https://travis-ci.org/rstudio/tensorflow/jobs/169892488#L1075). There's not much point in us doing that, since it'd be pretty much the whole package.

I'll try and pick this up again soon.
<details><summary>

Here's what I tried</summary>

<p>

First attempt:
added `libc6` to `apt_packages:` in `.travis.yml`;
but it was already at the most recent so same error

Second attempt:
added `dist: trusty` as in the `rstudio/tensorflow` travis build, in case either TF or the R API won't play nicely with earlier releases of linux;
but this failed as installation of rstudio/tensorflow from github couldn't find numpy

Third attempt:
updated the TF binary path to the most recent version on the TF site;
still couldn't find numpy

Fourth attempt:
copied over virtualenv part of rstudio/tensorflow travis installation script;
but couldn't even install R API

Fifth attempt:
copied travis setup from rstudio/tensorflow wholesale, installed R API and switched testing to gpflowr;
virtualenv apparently still not working...

</p></details>

**Comment by goldingn** [comment]
OK, I fixed the Travis build (Monday mornings are so much more effective than Friday evenings), and merged the fix with @NicolasDurrande's commits in #5, which is now merged. Closing this one.

Thanks  @NicolasDurrande!

**Pull request closed without merging**
